apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: ./proto
  contents:
  - path: vendor
    git:
      url: https://github.com/GaloyMoney/bria.git
      ref: 2a6c72f2ec211c972b05964f23c5938b6cf2ed7d
    includePaths:
    - proto/**/*
    newRootPath: proto
