// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.1
// 	protoc        v3.21.12
// source: api/bria.proto

package briav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImportXpubRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Xpub       string `protobuf:"bytes,2,opt,name=xpub,proto3" json:"xpub,omitempty"`
	Derivation string `protobuf:"bytes,3,opt,name=derivation,proto3" json:"derivation,omitempty"`
}

func (x *ImportXpubRequest) Reset() {
	*x = ImportXpubRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bria_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportXpubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportXpubRequest) ProtoMessage() {}

func (x *ImportXpubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bria_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportXpubRequest.ProtoReflect.Descriptor instead.
func (*ImportXpubRequest) Descriptor() ([]byte, []int) {
	return file_api_bria_proto_rawDescGZIP(), []int{0}
}

func (x *ImportXpubRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImportXpubRequest) GetXpub() string {
	if x != nil {
		return x.Xpub
	}
	return ""
}

func (x *ImportXpubRequest) GetDerivation() string {
	if x != nil {
		return x.Derivation
	}
	return ""
}

type ImportXpubResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ImportXpubResponse) Reset() {
	*x = ImportXpubResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bria_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportXpubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportXpubResponse) ProtoMessage() {}

func (x *ImportXpubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bria_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportXpubResponse.ProtoReflect.Descriptor instead.
func (*ImportXpubResponse) Descriptor() ([]byte, []int) {
	return file_api_bria_proto_rawDescGZIP(), []int{1}
}

func (x *ImportXpubResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SetSignerConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XpubRef string `protobuf:"bytes,1,opt,name=xpub_ref,json=xpubRef,proto3" json:"xpub_ref,omitempty"`
	// Types that are assignable to Config:
	//
	//	*SetSignerConfigRequest_Lnd
	Config isSetSignerConfigRequest_Config `protobuf_oneof:"config"`
}

func (x *SetSignerConfigRequest) Reset() {
	*x = SetSignerConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bria_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSignerConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSignerConfigRequest) ProtoMessage() {}

func (x *SetSignerConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bria_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSignerConfigRequest.ProtoReflect.Descriptor instead.
func (*SetSignerConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_bria_proto_rawDescGZIP(), []int{2}
}

func (x *SetSignerConfigRequest) GetXpubRef() string {
	if x != nil {
		return x.XpubRef
	}
	return ""
}

func (m *SetSignerConfigRequest) GetConfig() isSetSignerConfigRequest_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (x *SetSignerConfigRequest) GetLnd() *LndSignerConfig {
	if x, ok := x.GetConfig().(*SetSignerConfigRequest_Lnd); ok {
		return x.Lnd
	}
	return nil
}

type isSetSignerConfigRequest_Config interface {
	isSetSignerConfigRequest_Config()
}

type SetSignerConfigRequest_Lnd struct {
	Lnd *LndSignerConfig `protobuf:"bytes,2,opt,name=lnd,proto3,oneof"`
}

func (*SetSignerConfigRequest_Lnd) isSetSignerConfigRequest_Config() {}

type LndSignerConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoint       string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	CertBase64     string `protobuf:"bytes,2,opt,name=cert_base64,json=certBase64,proto3" json:"cert_base64,omitempty"`
	MacaroonBase64 string `protobuf:"bytes,3,opt,name=macaroon_base64,json=macaroonBase64,proto3" json:"macaroon_base64,omitempty"`
}

func (x *LndSignerConfig) Reset() {
	*x = LndSignerConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bria_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LndSignerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LndSignerConfig) ProtoMessage() {}

func (x *LndSignerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_bria_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LndSignerConfig.ProtoReflect.Descriptor instead.
func (*LndSignerConfig) Descriptor() ([]byte, []int) {
	return file_api_bria_proto_rawDescGZIP(), []int{3}
}

func (x *LndSignerConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *LndSignerConfig) GetCertBase64() string {
	if x != nil {
		return x.CertBase64
	}
	return ""
}

func (x *LndSignerConfig) GetMacaroonBase64() string {
	if x != nil {
		return x.MacaroonBase64
	}
	return ""
}

type SetSignerConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetSignerConfigResponse) Reset() {
	*x = SetSignerConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bria_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSignerConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSignerConfigResponse) ProtoMessage() {}

func (x *SetSignerConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bria_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSignerConfigResponse.ProtoReflect.Descriptor instead.
func (*SetSignerConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_bria_proto_rawDescGZIP(), []int{4}
}

type CreateWalletRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XpubRefs []string `protobuf:"bytes,2,rep,name=xpub_refs,json=xpubRefs,proto3" json:"xpub_refs,omitempty"`
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bria_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bria_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_bria_proto_rawDescGZIP(), []int{5}
}

func (x *CreateWalletRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWalletRequest) GetXpubRefs() []string {
	if x != nil {
		return x.XpubRefs
	}
	return nil
}

type CreateWalletResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateWalletResponse) Reset() {
	*x = CreateWalletResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bria_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletResponse) ProtoMessage() {}

func (x *CreateWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bria_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletResponse.ProtoReflect.Descriptor instead.
func (*CreateWalletResponse) Descriptor() ([]byte, []int) {
	return file_api_bria_proto_rawDescGZIP(), []int{6}
}

func (x *CreateWalletResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type NewAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletName string `protobuf:"bytes,1,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
}

func (x *NewAddressRequest) Reset() {
	*x = NewAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bria_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAddressRequest) ProtoMessage() {}

func (x *NewAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bria_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAddressRequest.ProtoReflect.Descriptor instead.
func (*NewAddressRequest) Descriptor() ([]byte, []int) {
	return file_api_bria_proto_rawDescGZIP(), []int{7}
}

func (x *NewAddressRequest) GetWalletName() string {
	if x != nil {
		return x.WalletName
	}
	return ""
}

type NewAddressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *NewAddressResponse) Reset() {
	*x = NewAddressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bria_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAddressResponse) ProtoMessage() {}

func (x *NewAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bria_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAddressResponse.ProtoReflect.Descriptor instead.
func (*NewAddressResponse) Descriptor() ([]byte, []int) {
	return file_api_bria_proto_rawDescGZIP(), []int{8}
}

func (x *NewAddressResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetWalletBalanceSummaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletName string `protobuf:"bytes,1,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
}

func (x *GetWalletBalanceSummaryRequest) Reset() {
	*x = GetWalletBalanceSummaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bria_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWalletBalanceSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalanceSummaryRequest) ProtoMessage() {}

func (x *GetWalletBalanceSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bria_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalanceSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetWalletBalanceSummaryRequest) Descriptor() ([]byte, []int) {
	return file_api_bria_proto_rawDescGZIP(), []int{9}
}

func (x *GetWalletBalanceSummaryRequest) GetWalletName() string {
	if x != nil {
		return x.WalletName
	}
	return ""
}

type GetWalletBalanceSummaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PendingIncoming    uint64 `protobuf:"varint,1,opt,name=pending_incoming,json=pendingIncoming,proto3" json:"pending_incoming,omitempty"`
	EncumberedFees     uint64 `protobuf:"varint,2,opt,name=encumbered_fees,json=encumberedFees,proto3" json:"encumbered_fees,omitempty"`
	CurrentSettled     uint64 `protobuf:"varint,3,opt,name=current_settled,json=currentSettled,proto3" json:"current_settled,omitempty"`
	EncumberedOutgoing uint64 `protobuf:"varint,4,opt,name=encumbered_outgoing,json=encumberedOutgoing,proto3" json:"encumbered_outgoing,omitempty"`
	PendingOutgoing    uint64 `protobuf:"varint,5,opt,name=pending_outgoing,json=pendingOutgoing,proto3" json:"pending_outgoing,omitempty"`
	PendingFees        uint64 `protobuf:"varint,6,opt,name=pending_fees,json=pendingFees,proto3" json:"pending_fees,omitempty"`
}

func (x *GetWalletBalanceSummaryResponse) Reset() {
	*x = GetWalletBalanceSummaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bria_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWalletBalanceSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalanceSummaryResponse) ProtoMessage() {}

func (x *GetWalletBalanceSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bria_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalanceSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetWalletBalanceSummaryResponse) Descriptor() ([]byte, []int) {
	return file_api_bria_proto_rawDescGZIP(), []int{10}
}

func (x *GetWalletBalanceSummaryResponse) GetPendingIncoming() uint64 {
	if x != nil {
		return x.PendingIncoming
	}
	return 0
}

func (x *GetWalletBalanceSummaryResponse) GetEncumberedFees() uint64 {
	if x != nil {
		return x.EncumberedFees
	}
	return 0
}

func (x *GetWalletBalanceSummaryResponse) GetCurrentSettled() uint64 {
	if x != nil {
		return x.CurrentSettled
	}
	return 0
}

func (x *GetWalletBalanceSummaryResponse) GetEncumberedOutgoing() uint64 {
	if x != nil {
		return x.EncumberedOutgoing
	}
	return 0
}

func (x *GetWalletBalanceSummaryResponse) GetPendingOutgoing() uint64 {
	if x != nil {
		return x.PendingOutgoing
	}
	return 0
}

func (x *GetWalletBalanceSummaryResponse) GetPendingFees() uint64 {
	if x != nil {
		return x.PendingFees
	}
	return 0
}

type CreateBatchGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateBatchGroupRequest) Reset() {
	*x = CreateBatchGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bria_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBatchGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBatchGroupRequest) ProtoMessage() {}

func (x *CreateBatchGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bria_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBatchGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateBatchGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_bria_proto_rawDescGZIP(), []int{11}
}

func (x *CreateBatchGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateBatchGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateBatchGroupResponse) Reset() {
	*x = CreateBatchGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bria_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBatchGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBatchGroupResponse) ProtoMessage() {}

func (x *CreateBatchGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bria_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBatchGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateBatchGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_bria_proto_rawDescGZIP(), []int{12}
}

func (x *CreateBatchGroupResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type QueuePayoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletName     string `protobuf:"bytes,1,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	BatchGroupName string `protobuf:"bytes,2,opt,name=batch_group_name,json=batchGroupName,proto3" json:"batch_group_name,omitempty"`
	// Types that are assignable to Destination:
	//
	//	*QueuePayoutRequest_OnchainAddress
	Destination isQueuePayoutRequest_Destination `protobuf_oneof:"destination"`
	Satoshis    uint64                           `protobuf:"varint,4,opt,name=satoshis,proto3" json:"satoshis,omitempty"`
}

func (x *QueuePayoutRequest) Reset() {
	*x = QueuePayoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bria_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueuePayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuePayoutRequest) ProtoMessage() {}

func (x *QueuePayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bria_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuePayoutRequest.ProtoReflect.Descriptor instead.
func (*QueuePayoutRequest) Descriptor() ([]byte, []int) {
	return file_api_bria_proto_rawDescGZIP(), []int{13}
}

func (x *QueuePayoutRequest) GetWalletName() string {
	if x != nil {
		return x.WalletName
	}
	return ""
}

func (x *QueuePayoutRequest) GetBatchGroupName() string {
	if x != nil {
		return x.BatchGroupName
	}
	return ""
}

func (m *QueuePayoutRequest) GetDestination() isQueuePayoutRequest_Destination {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (x *QueuePayoutRequest) GetOnchainAddress() string {
	if x, ok := x.GetDestination().(*QueuePayoutRequest_OnchainAddress); ok {
		return x.OnchainAddress
	}
	return ""
}

func (x *QueuePayoutRequest) GetSatoshis() uint64 {
	if x != nil {
		return x.Satoshis
	}
	return 0
}

type isQueuePayoutRequest_Destination interface {
	isQueuePayoutRequest_Destination()
}

type QueuePayoutRequest_OnchainAddress struct {
	OnchainAddress string `protobuf:"bytes,3,opt,name=onchain_address,json=onchainAddress,proto3,oneof"`
}

func (*QueuePayoutRequest_OnchainAddress) isQueuePayoutRequest_Destination() {}

type QueuePayoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *QueuePayoutResponse) Reset() {
	*x = QueuePayoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_bria_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueuePayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuePayoutResponse) ProtoMessage() {}

func (x *QueuePayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bria_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuePayoutResponse.ProtoReflect.Descriptor instead.
func (*QueuePayoutResponse) Descriptor() ([]byte, []int) {
	return file_api_bria_proto_rawDescGZIP(), []int{14}
}

func (x *QueuePayoutResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_bria_proto protoreflect.FileDescriptor

var file_api_bria_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x72, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x62, 0x72, 0x69, 0x61, 0x2e,
	0x76, 0x31, 0x22, 0x5b, 0x0a, 0x11, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x58, 0x70, 0x75, 0x62,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x78,
	0x70, 0x75, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x78, 0x70, 0x75, 0x62, 0x12,
	0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x72, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x72, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x24, 0x0a, 0x12, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x58, 0x70, 0x75, 0x62, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x74, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x78, 0x70, 0x75, 0x62, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x78, 0x70, 0x75, 0x62, 0x52, 0x65, 0x66, 0x12, 0x35, 0x0a, 0x03, 0x6c, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x62, 0x72, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6e, 0x64, 0x53, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x03, 0x6c, 0x6e,
	0x64, 0x42, 0x08, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x77, 0x0a, 0x0f, 0x4c,
	0x6e, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1a,
	0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x65,
	0x72, 0x74, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x65, 0x72, 0x74, 0x42, 0x61, 0x73, 0x65, 0x36, 0x34, 0x12, 0x27, 0x0a, 0x0f, 0x6d,
	0x61, 0x63, 0x61, 0x72, 0x6f, 0x6f, 0x6e, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x61, 0x63, 0x61, 0x72, 0x6f, 0x6f, 0x6e, 0x42, 0x61,
	0x73, 0x65, 0x36, 0x34, 0x22, 0x19, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x46, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x78, 0x70,
	0x75, 0x62, 0x5f, 0x72, 0x65, 0x66, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x78,
	0x70, 0x75, 0x62, 0x52, 0x65, 0x66, 0x73, 0x22, 0x26, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x34, 0x0a, 0x11, 0x4e, 0x65, 0x77, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x4e, 0x65, 0x77, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x41, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x9d, 0x02, 0x0a, 0x1f, 0x47, 0x65, 0x74,
	0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x10,
	0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x49,
	0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x6e, 0x63, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x66, 0x65, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0e, 0x65, 0x6e, 0x63, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x65, 0x64, 0x46, 0x65, 0x65, 0x73,
	0x12, 0x27, 0x0a, 0x0f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x74, 0x74,
	0x6c, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x64, 0x12, 0x2f, 0x0a, 0x13, 0x65, 0x6e, 0x63,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x6f, 0x75, 0x74, 0x67, 0x6f, 0x69, 0x6e, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x12, 0x65, 0x6e, 0x63, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x65, 0x64, 0x4f, 0x75, 0x74, 0x67, 0x6f, 0x69, 0x6e, 0x67, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x6f, 0x75, 0x74, 0x67, 0x6f, 0x69, 0x6e, 0x67, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4f, 0x75, 0x74,
	0x67, 0x6f, 0x69, 0x6e, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x5f, 0x66, 0x65, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x70, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x46, 0x65, 0x65, 0x73, 0x22, 0x2d, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2a, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0xb5, 0x01, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x75, 0x65, 0x50, 0x61, 0x79,
	0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x62,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x62, 0x61, 0x74, 0x63, 0x68, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x0f, 0x6f, 0x6e, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x0e, 0x6f, 0x6e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x61, 0x74, 0x6f, 0x73, 0x68, 0x69, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x73, 0x61, 0x74, 0x6f, 0x73, 0x68, 0x69, 0x73, 0x42, 0x0d, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x25, 0x0a, 0x13, 0x51,
	0x75, 0x65, 0x75, 0x65, 0x50, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x32, 0xdc, 0x05, 0x0a, 0x0b, 0x42, 0x72, 0x69, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x59, 0x0a, 0x0a, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x58, 0x70, 0x75, 0x62,
	0x12, 0x23, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x62, 0x72, 0x69, 0x61,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x58, 0x70, 0x75, 0x62, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x62, 0x72, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x58,
	0x70, 0x75, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x68, 0x0a,
	0x0f, 0x53, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x28, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x62, 0x72, 0x69, 0x61,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x62, 0x72, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65,
	0x74, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x25, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x62, 0x72, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x62, 0x72, 0x69, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x80, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x12, 0x30, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x62, 0x72, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x62, 0x72, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x0a, 0x4e,
	0x65, 0x77, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x23, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x62, 0x72, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x62, 0x72, 0x69, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x4e, 0x65, 0x77, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6b, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x29, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x62, 0x72, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x62, 0x72, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x75, 0x65, 0x50, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x12, 0x24, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x62, 0x72,
	0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x50, 0x61, 0x79, 0x6f, 0x75,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x62, 0x72, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x50, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x47, 0x61, 0x6c, 0x6f, 0x79, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x2f, 0x74, 0x65, 0x72, 0x72, 0x61,
	0x66, 0x6f, 0x72, 0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2d, 0x62, 0x72,
	0x69, 0x61, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x62, 0x72, 0x69, 0x61, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_bria_proto_rawDescOnce sync.Once
	file_api_bria_proto_rawDescData = file_api_bria_proto_rawDesc
)

func file_api_bria_proto_rawDescGZIP() []byte {
	file_api_bria_proto_rawDescOnce.Do(func() {
		file_api_bria_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_bria_proto_rawDescData)
	})
	return file_api_bria_proto_rawDescData
}

var file_api_bria_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_bria_proto_goTypes = []interface{}{
	(*ImportXpubRequest)(nil),               // 0: services.bria.v1.ImportXpubRequest
	(*ImportXpubResponse)(nil),              // 1: services.bria.v1.ImportXpubResponse
	(*SetSignerConfigRequest)(nil),          // 2: services.bria.v1.SetSignerConfigRequest
	(*LndSignerConfig)(nil),                 // 3: services.bria.v1.LndSignerConfig
	(*SetSignerConfigResponse)(nil),         // 4: services.bria.v1.SetSignerConfigResponse
	(*CreateWalletRequest)(nil),             // 5: services.bria.v1.CreateWalletRequest
	(*CreateWalletResponse)(nil),            // 6: services.bria.v1.CreateWalletResponse
	(*NewAddressRequest)(nil),               // 7: services.bria.v1.NewAddressRequest
	(*NewAddressResponse)(nil),              // 8: services.bria.v1.NewAddressResponse
	(*GetWalletBalanceSummaryRequest)(nil),  // 9: services.bria.v1.GetWalletBalanceSummaryRequest
	(*GetWalletBalanceSummaryResponse)(nil), // 10: services.bria.v1.GetWalletBalanceSummaryResponse
	(*CreateBatchGroupRequest)(nil),         // 11: services.bria.v1.CreateBatchGroupRequest
	(*CreateBatchGroupResponse)(nil),        // 12: services.bria.v1.CreateBatchGroupResponse
	(*QueuePayoutRequest)(nil),              // 13: services.bria.v1.QueuePayoutRequest
	(*QueuePayoutResponse)(nil),             // 14: services.bria.v1.QueuePayoutResponse
}
var file_api_bria_proto_depIdxs = []int32{
	3,  // 0: services.bria.v1.SetSignerConfigRequest.lnd:type_name -> services.bria.v1.LndSignerConfig
	0,  // 1: services.bria.v1.BriaService.ImportXpub:input_type -> services.bria.v1.ImportXpubRequest
	2,  // 2: services.bria.v1.BriaService.SetSignerConfig:input_type -> services.bria.v1.SetSignerConfigRequest
	5,  // 3: services.bria.v1.BriaService.CreateWallet:input_type -> services.bria.v1.CreateWalletRequest
	9,  // 4: services.bria.v1.BriaService.GetWalletBalanceSummary:input_type -> services.bria.v1.GetWalletBalanceSummaryRequest
	7,  // 5: services.bria.v1.BriaService.NewAddress:input_type -> services.bria.v1.NewAddressRequest
	11, // 6: services.bria.v1.BriaService.CreateBatchGroup:input_type -> services.bria.v1.CreateBatchGroupRequest
	13, // 7: services.bria.v1.BriaService.QueuePayout:input_type -> services.bria.v1.QueuePayoutRequest
	1,  // 8: services.bria.v1.BriaService.ImportXpub:output_type -> services.bria.v1.ImportXpubResponse
	4,  // 9: services.bria.v1.BriaService.SetSignerConfig:output_type -> services.bria.v1.SetSignerConfigResponse
	6,  // 10: services.bria.v1.BriaService.CreateWallet:output_type -> services.bria.v1.CreateWalletResponse
	10, // 11: services.bria.v1.BriaService.GetWalletBalanceSummary:output_type -> services.bria.v1.GetWalletBalanceSummaryResponse
	8,  // 12: services.bria.v1.BriaService.NewAddress:output_type -> services.bria.v1.NewAddressResponse
	12, // 13: services.bria.v1.BriaService.CreateBatchGroup:output_type -> services.bria.v1.CreateBatchGroupResponse
	14, // 14: services.bria.v1.BriaService.QueuePayout:output_type -> services.bria.v1.QueuePayoutResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_bria_proto_init() }
func file_api_bria_proto_init() {
	if File_api_bria_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_bria_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportXpubRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bria_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportXpubResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bria_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSignerConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bria_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LndSignerConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bria_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSignerConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bria_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWalletRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bria_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWalletResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bria_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bria_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewAddressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bria_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWalletBalanceSummaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bria_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWalletBalanceSummaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bria_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBatchGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bria_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBatchGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bria_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueuePayoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_bria_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueuePayoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_bria_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*SetSignerConfigRequest_Lnd)(nil),
	}
	file_api_bria_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*QueuePayoutRequest_OnchainAddress)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_bria_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_bria_proto_goTypes,
		DependencyIndexes: file_api_bria_proto_depIdxs,
		MessageInfos:      file_api_bria_proto_msgTypes,
	}.Build()
	File_api_bria_proto = out.File
	file_api_bria_proto_rawDesc = nil
	file_api_bria_proto_goTypes = nil
	file_api_bria_proto_depIdxs = nil
}
